def import_all_models() -> None:
    import app.modules.accounting.models.account  # noqa: F401
    import app.modules.accounting.models.journal_entry  # noqa: F401
    import app.modules.accounting.models.journal_line  # noqa: F401
    import app.modules.audit.models.audit_event  # noqa: F401
    import app.modules.beneficiary.models.beneficiary  # noqa: F401
    import app.modules.budget.models.budget  # noqa: F401
    import app.modules.budget.models.budget_line  # noqa: F401
    import app.modules.delivery.models.delivery_order  # noqa: F401
    import app.modules.delivery.models.delivery_proof  # noqa: F401
    import app.modules.document.models.document  # noqa: F401
    import app.modules.document.models.document_link  # noqa: F401
    import app.modules.document.models.document_version  # noqa: F401
    import app.modules.geography.models.school  # noqa: F401
    import app.modules.identity.models.user  # noqa: F401
    import app.modules.identity.models.user_sppg_access  # noqa: F401
    import app.modules.integration.models.external_system  # noqa: F401
    import app.modules.integration.models.integration_credential  # noqa: F401
    import app.modules.integration.models.sync_log  # noqa: F401
    import app.modules.inventory.models.inventory_balance  # noqa: F401
    import app.modules.inventory.models.inventory_transaction  # noqa: F401
    import app.modules.inventory.models.warehouse  # noqa: F401
    import app.modules.meal_plan.models.meal_plan  # noqa: F401
    import app.modules.program.models.program  # noqa: F401
    import app.modules.program.models.program_period  # noqa: F401
    import app.modules.program.models.program_sppg  # noqa: F401
    import app.modules.program.models.program_tenant  # noqa: F401
    import app.modules.product.models.product  # noqa: F401
    import app.modules.production.models.production_material_consumption  # noqa: F401
    import app.modules.production.models.production_order  # noqa: F401
    import app.modules.procurement.models.purchase_request  # noqa: F401
    import app.modules.procurement.models.purchase_request_line  # noqa: F401
    import app.modules.procurement.models.goods_receipt  # noqa: F401
    import app.modules.procurement.models.goods_receipt_line  # noqa: F401
    import app.modules.procurement.models.supplier_invoice  # noqa: F401
    import app.modules.procurement.models.supplier_invoice_line  # noqa: F401
    import app.modules.procurement.models.supplier_payment  # noqa: F401
    import app.modules.quality.models.qc_inspection  # noqa: F401
    import app.modules.quality.models.qc_inspection_line  # noqa: F401
    import app.modules.recipe.models.recipe  # noqa: F401
    import app.modules.recipe.models.recipe_line  # noqa: F401
    import app.modules.sppg.models.sppg  # noqa: F401
    import app.modules.tenant.models.tenant  # noqa: F401
    import app.modules.uom.models.uom  # noqa: F401
    import app.modules.workflow.models.workflow_definition  # noqa: F401
    import app.modules.workflow.models.workflow_history  # noqa: F401
    import app.modules.workflow.models.workflow_instance  # noqa: F401
    import app.modules.workflow.models.workflow_transition  # noqa: F401
